frase = '  Curso em Vídeo Python  '
print(frase[3])
print(frase[4:13])
print(frase[:13])
print(frase[13:])
print(frase[1:15])
print(frase[0:15:2])
print("""Testando funcionalidade para print textos longos.
Isso parece bastante útil!!!""")
print(frase.count('o'))
print(len(frase.strip()))
print(frase.replace('Python', 'Android'))
print('Curso' in frase)
print(frase.find('Curso'))
print(frase.split())
dividido = frase.split()
print(dividido[0])
print(dividido[2][3])
